name: PR Checks

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: ${{ env.RUST_TOOLCHAIN }}
                  components: rustfmt, clippy

            - name: Cache Rust dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-

            - name: Install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libudev-dev pkg-config

            - name: Check formatting
              run: make fmt

            - name: Run linter
              run: make lint

            - name: Build all apps
              run: make build

            - name: Unit test all apps and crates
              run: make unit-test